### ISSUE TITLE
no background sounds on mobile

### ISSUE THREAD

**Issue by rdub80** [rdub80/gravr-a11y-demo#3]
preloading screen to force a trigger to launch sound?

**Comment by rdub80** [comment]
Background sounds don't work on mobile iOS 
On mobile iOS TTS only starts working after click on beacon (then it works even for hover events)
Step sounds don't work on either mobile iOS or Android

Let's try a loading screen (no slideshow needed) with a simple button "Start VR" based on this component https://github.com/gladeye/aframe-preloader-component first to see if that fixes things. We won't need bootstrap or fontawesome, just a spinner gif https://upload.wikimedia.org/wikipedia/commons/b/b1/Loading_icon.gif and <button> will do.

**Comment by alwell-kevin** [comment]
In progress...

**Comment by alwell-kevin** [comment]
Can confirm audio.play() broken feature due to lack of trusted User Gesture.

**Comment by alwell-kevin** [comment]
All sounds Functioning... Complete Pending tests on IOS

**Comment by rdub80** [comment]
works with headphones - tested on 2 iphones
