### ISSUE TITLE
Beacon & Beacon-control Components

### ISSUE THREAD

**Issue by rdub80** [rdub80/gravr-a11y-demo#5]
### Please double check functionality for this intended behavior across android&iOS mobile
- when _mouseenter_ on **hoverArea** play `lookingAt = "You are looking at the Beacon " + this.data.description`
- when _mouseout_  on **hoverArea** stop/cancel playing lookingAt
- when click on **hoverArea**:
1. stop/cancel playing lookingAt and start playing `tts = "You're walking towards the Beacon " + text;`
2. start playing looped sounds/step.mp3 effect until **navigation-end** (the camera arrived at the beacon and stopped)
3. turn  **hoverArea** invisible when the beacon is active (when camera is at the beacon)

Issues
**readOnce** function doesn't recognize if this.data.description changes. tts only runs once when clicking on a beacon but not anymore when you click on another beacon

**Comment by alwell-kevin** [comment]
In Progress...

**Comment by alwell-kevin** [comment]
Issue Resolved pending approval @rdub80

**Comment by rdub80** [comment]
@alwell-kevin this is great stuff! I love the steps solution now I can increase speed and make the person run... 2 steps per meter is a good average for a stride.
I did adjust the hiding script a little and changed the step sound mp3. 
Great job!
