### ISSUE TITLE
steps.mp3 sound won't work on github page desktop or mobile

### ISSUE THREAD

**Issue by rdub80** [rdub80/gravr-a11y-demo#8]
here is someone that had the same issue and solved it via rawgit:
https://stackoverflow.com/questions/31353711/source-an-audio-file-in-repo-on-github-pages

<img width="766" alt="screen shot 2017-10-04 at 1 23 00 am" src="https://user-images.githubusercontent.com/347570/31161197-85c13116-a8a3-11e7-8022-94cda03e8433.png">

however all other sound works - could you take a look and investigate? But don't spend too much time on it :-)

**Comment by alwell-kevin** [comment]
Resolved.
